### ISSUE TITLE
Cleanup input / forms styling

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#105]
This needs a good cleanup, including variables, variable names and so on.

Remember to make great **documentation, and examples** (in the examples folder).

**Comment by Dan9boi** [comment]
Make the markup and styling based on beneath best practices.

**Comment by shp-novicell** [comment]
Todo:

- Validation
- Documentation for markup (autofill, autocorrect etc.)
- Testing

**Comment by Dan9boi** [comment]
@shp-novicell due to MIA, this issue is assigned to @heense....

**Comment by Dan9boi** [comment]
@Havmoeller can you merge the forms input styling and check the validation script, in fractal?

**Comment by heense** [comment]
Fixed
