### ISSUE TITLE
Look into gulp-clean-css

### ISSUE THREAD

**Issue by hesselberg** [Novicell/novicell-frontend#12]
Might be able to save some space by adding gulp-clean-css after cssnano in our styles task.

**Comment by hesselberg** [comment]
Needs to be further investigated, and discussed if this has any impact at all. By the looks of it, it seems it does exactly the same as css nano

**Comment by Dan9boi** [comment]
@Nesuarg can you investigate this? Can gulp-clean-css do anything, that we're not already doing with css nano?

**Comment by Dan9boi** [comment]
ping @hesselberg can you make time for this issue, before due date?

**Comment by hesselberg** [comment]
Yes :) I'll make time for it next week

**Comment by Dan9boi** [comment]
@hesselberg ...

**Comment by hesselberg** [comment]
:/

**Comment by Dan9boi** [comment]
We've decided that cssnano covers what gulp-clean-css does, so, we'll not look further into it.
