### ISSUE TITLE
PostCss + CSS Next

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#126]
Use PostCss + CSS Next instead of LESSCSS (or SASS) for using all the new cool features of CSS4 spec and learning real CSS instead of an arbitrary css variant like SASS.
What is your opponion? @Novicell/team-contributers

**Comment by shp-novicell** [comment]
Check it out:
http://postcss.org/
http://cssnext.io/

**Comment by Dan9boi** [comment]
done due to #146
