### ISSUE TITLE
Revisit breakpoints

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#128]
Due to this blogpost, maybe we should revisit our breakpoints:
https://medium.freecodecamp.com/the-100-correct-way-to-do-css-breakpoints-88d6a5ba1862

We could also look at [how bootstrap 4 is doing their breakpoints](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss):
```scss
// Grid breakpoints
//
// Define the minimum dimensions at which your layout will change,
// adapting to different screen sizes, for use in media queries.

$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px
) !default;
@include _assert-ascending($grid-breakpoints, "$grid-breakpoints");
@include _assert-starts-at-zero($grid-breakpoints);
```
**And also add an `XL`-breakpoint.**

**Comment by shp-novicell** [comment]
Duplicate: https://github.com/Novicell/novicell-frontend/issues/40
