### ISSUE TITLE
Refactor novicell.embed.js

### ISSUE THREAD

**Issue by shp-novicell** [Novicell/novicell-frontend#135]
Use new syntax: https://github.com/Novicell/novicell-frontend/issues/111

**Comment by Dan9boi** [comment]
And make new repo

**Comment by soreng** [comment]
New repo is made, 1st commit comming later today

**Comment by Dan9boi** [comment]
@soreng when do we see some code?

**Comment by Dan9boi** [comment]
@soreng sup?
