### ISSUE TITLE
Task to make favicons

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#143]
Make it easier to make favicons the right way, and the right sizes.

Mayer use this node.js cli tool: http://realfavicongenerator.net/favicon/node_cli#.WUDp-IF5OEe

**Comment by KimDolleris** [comment]
Can we start with adding .ico to the copy task? :)

**Comment by Dan9boi** [comment]
@KimDolleris what do you need that for?
According to this website, favicons should be placed in the root of the website: https://realfavicongenerator.net/faq#.WdKG42iCyUk

> Internet Explorer looks for **favicon.ico at the root of the web site.** Granted: this is because we ask you to not declare favicon.ico.

**Comment by Dan9boi** [comment]
https://github.com/Novicell/novicell-frontend/pull/150

**Comment by Dan9boi** [comment]
done due to #150
