### ISSUE TITLE
Property naming in Fractal context data

### ISSUE THREAD

**Issue by magnify** [Novicell/novicell-frontend#152]
To avoid issues with Handlebars.NET integration property naming should be in CamelCase and without dashes.

@K3llr do you have input and maybe an example?

**Comment by Dan9boi** [comment]
Cool, i've notified everyone in the team.

**Comment by Dan9boi** [comment]
did you fix this in the current codebase @heense ?

**Comment by Dan9boi** [comment]
or did you @jhavmoeller ?

**Comment by tbb2** [comment]
@Dan9boi is this still relevant or could we just close the issue?
