### ISSUE TITLE
Spaces when including patterns

### ISSUE THREAD

**Issue by magnify** [Novicell/novicell-frontend#153]
To avoid issues with Handlebars.NET integration we should not use spaces when including patterns.

Do: {{> @MyPattern='--centered' }}
Don't do: {{> @MyPattern = '--centered' }}

Maybe we can do automate this somehow?

Ping @K3llr

**Comment by Dan9boi** [comment]
Cool it's noted.

**Comment by shp-novicell** [comment]
Done
