### ISSUE TITLE
Make settings for jshint

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#159]
Setup some settings for [jshint](http://jshint.com/docs/)
Make documentation for our choices, in the [frontenddocs](https://novicell.github.io/frontenddocs/)

Look at removing js codestyle...

**Comment by jhavmoeller** [comment]
We should also get this up at running with the onSave event
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**eslint.autoFixOnSave**

**Comment by Dan9boi** [comment]
This is added to the new version #273
