### ISSUE TITLE
Fractal guidelines

### ISSUE THREAD

**Issue by tbb2** [Novicell/novicell-frontend#163]
1. Der mangler beskrivelse af helpers-mappen, hvor grid'et fx ligger.

1. Under Patterns structure i forklaringen af json-filen - er dette ikke en bedre forklaring af hvordan vi vil have modifiers?:
We don't use the config for creating modifiers. If a modifier is needed a new variant handlebars file should always be created. This way we can keep track of modifiers both by looking in fractal but also in our file tree.

**Comment by Dan9boi** [comment]
Yes that's great spotted. Can you make the changes, then I would love to review @tbb2  :)

**Comment by Dan9boi** [comment]
@heense did you merge these changes to the wiki, and removed it from fractal docs (repo)?

**Comment by Dan9boi** [comment]
FYI: helpers folder is gone by now :)

**Comment by Dan9boi** [comment]
@tbb2 notice the milestone ends on tuesday :)

**Comment by tbb2** [comment]
@Dan9boi changed the wiki according to 2) - what should I do with this issue then, do you close it after reviewing?

**Comment by Dan9boi** [comment]
great job :)
