### ISSUE TITLE
PostCSS guidelines variabler

### ISSUE THREAD

**Issue by tbb2** [Novicell/novicell-frontend#165]
Vi burde lave eksemplet om så det var en farve i stedet for font-weight, folk kan misforstå og tro det er standard at lave variabler til font-weight. Måske burde der også stå noget om fall-back værdier, det bør man altid lave, hvis man refererer til en variabel fra en anden fil?

Ny tekst og eksempel:

Variables are native CSS custom properties. All variable names should be in spinal-case, just like in CSS classes.

If you use a variable defined in another css file, you must reference the variable in the current file, and then you must add a fallback value in the definition - see the variable "--some-class-background" in the example below.

You can use variables like this :

Setting

:root {
    --some-class-color: red;
    --some-class-background: var(--color-primary, #fff);
}
Getting

.some-class {
    color: var(--some-class-color);
    background var(--some-class-background);

}

**Comment by Dan9boi** [comment]
done, i've also added an extra example for telling that a variable can be anything:
https://github.com/Novicell/novicell-frontend/wiki/PostCSS-guidelines#variables
