### ISSUE TITLE
Fix grammatical errors in Fractal documentation

### ISSUE THREAD

**Issue by jhavmoeller** [Novicell/novicell-frontend#167]
There are some grammatical errors in the documentation.

**Comment by Dan9boi** [comment]
Please fix @ramiejleh 💯

**Comment by Dan9boi** [comment]
@ramiejleh note that this milestone ends at 28th of feb. :)
Please fix!

**Comment by ramiejleh** [comment]
Grammar and spelling errors should be fixed now
