### ISSUE TITLE
Do we need a datepicker?

### ISSUE THREAD

**Issue by Bjornnyborg** [Novicell/novicell-frontend#184]
Skal vi måske have en datepicker i vores frontend pakke?

**Comment by Dan9boi** [comment]
Yup

https://beneath.invisionapp.com/d/main/#/console/10395794/272964021/preview

**Comment by Bjornnyborg** [comment]
Ive made a datepicker based on flatpickr #281 
It doesnt look a lot like the invision design, due to the complexity of styling flatpickr.
