### ISSUE TITLE
Product image zoom

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#206]
It would be great to have an product image zoom effect, ready for implementation.
This could be just a class and some dependencies to add.

Look at this page for an example of a great implementation:
[etq-amsterdam](https://www.etq-amsterdam.com/store/product/men/sonic-white/)
Look out for too many dependencies, and their payloads.

**Comment by Dan9boi** [comment]
@Nyfjeld @jefctilsted what is the status for this issue?

**Comment by Bjornnyborg** [comment]
Closed, default components is moved to: https://github.com/Novicell/novicell-components
