### ISSUE TITLE
Product page

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#207]
I would be cool to have a product page, which we can reuse.
Here's a great example: [Philipson-Club](https://beneath.invisionapp.com/share/P6G31O0TNRU#/283779270_philipson-Club-Smagekasse-Produkt)

Start by analysing the layout, dividing it into atoms/molecules/organisms, and then make one component at a time.

**Comment by Dan9boi** [comment]
@Nyfjeld @jefctilsted what is the status for this issue?

**Comment by Bjornnyborg** [comment]
Closed, default components is moved to: https://github.com/Novicell/novicell-components
