### ISSUE TITLE
Background video pattern

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#218]
Make a new pattern for inserting background video.
* Make the default pattern as Novicell.dk.
* Make another variant, using vimeo and autoplay
* Make yet another variant using youtube, [preferably without youtube branding](https://codepen.io/lentilz/pen/mPOKdG)
* Make sure to test it on mobile!

**Comment by daniel-doktor** [comment]
@Dan9boi  The background video for youtube is not responsive and the video can be controlled when clicked.

The background video for Vimeo – when the video container is made taller – you can see the vimeo controls – further more you can also control the video by clicking it (start/ stop)

**Comment by Dan9boi** [comment]
Vimeo loads the video om mobile. Maybe the different types of videos should behave the same (show fallback image on mobile)

**Comment by Dan9boi** [comment]
Make sure to test on real mobile devices aswell.
Please test the vimeo scaling by using a different video, with people or something that needs a special scaling/cropping

**Comment by Henrikschytze** [comment]
- [ ] Make YT background responsive
- [ ] Remove every control possible from both YT and Vimeo
- [ ] Avoid making network requests when playing on devices that do not have the required width for videos
- [ ] Fix Vimeo scaling

**Comment by Dan9boi** [comment]
Great job @Henrikschytze 💯 
Can you fix the merge conflicts?

**Comment by Dan9boi** [comment]
done in #239
