### ISSUE TITLE
icons.json is not being generated

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#22]
icons.json is not being generated, after variables is made in the config file. Something is wrong with it. I can _cosole.log_ the object of the icons and the path, but it doesn't work.

Please fix!

**Comment by marklonquist** [comment]
Well ain't that some s**t :)

**Comment by marklonquist** [comment]
The jsonDistPath was never returned from the config file, so it was undefined in the task for icons.
