### ISSUE TITLE
Gulp dosn't work with fonts

### ISSUE THREAD

**Issue by MKAndersen** [Novicell/novicell-frontend#233]
The gulp setup done't compile fronts from assets to dist. Causing probelms since it can't find the fonts

**Comment by Bjornnyborg** [comment]
I've just tested this, i placed some fonts in "assets/fonts" and then ran "gulp", and it copied the fonts successfully into the "dist/fonts" folder.

Is this still an issue?

**Comment by Dan9boi** [comment]
@MKAndersen can you describe how to reproduce?
