### ISSUE TITLE
Multi level navigation

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#238]
Mobile multi level navigation:  <insert link>
Desktop multi level navigation: <insert link>

@KimDolleris

**Comment by macimuz** [comment]
How to solve some of the classic issues e.g. flickering:
https://baymard.com/blog/dropdown-menu-flickering-issue

**Comment by Bjornnyborg** [comment]
Closed, components now live at https://github.com/Novicell/novicell-components/
Repost issue on new repo, if its still a request.
