### ISSUE TITLE
Icons can't change fill

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#24]
We have a problem with icons that have inline "fill", can't have their "fill" overritten by CSS.
Therefore we need to remove the inline "fill"-attribute on all svg's before adding them to the sprite.

The problem is similar to this: https://github.com/jkphl/svg-sprite/issues/121

Please fix :)

**Comment by marklonquist** [comment]
I need a file which has inline fill for testing

**Comment by Dan9boi** [comment]
@marklonquist here is a svg for testing.
[inline-fill-svg.zip](https://github.com/Novicell/novicell-frontend/files/370899/inline-fill-svg.zip)

**Comment by hesselberg** [comment]
@Dan9boi @marklonquist all working as intended? If so, close :)
