### ISSUE TITLE
Make our design system into a product

### ISSUE THREAD

**Issue by macimuz** [Novicell/novicell-frontend#240]
https://frontend.novicell.cloud/

We need to make this much better e.g: http://www.carbondesignsystem.com/

Its much more presentable, has loads of examples, best practices and even sketch files for download.

Our design system could (should) be made into a product that our customers wish to buy.

Also look at Googles Material Design system. It also is great at explaining the usage and showing best practices etc etc.

https://material.io/design/

It would be awesome to be able to show real and live examples of forms and much more. Also, we would save a lot of time not having to document i.e. forms (in each design).

**Comment by Bjornnyborg** [comment]
@macimuz Ive updated the frontpage a bit, and set the project up, so that we can make a custom frontpage on https://frontend.novicell.cloud/, could you do a design for the page? Then i will code it.

**Comment by Bjornnyborg** [comment]
Closed, components now live at https://github.com/Novicell/novicell-components/
Repost issue on new repo, if its still a request.
