### ISSUE TITLE
Responsive filters

### ISSUE THREAD

**Issue by macimuz** [Novicell/novicell-frontend#243]
In my opinion we really need a large and refined set of filters (ecommerce and much more) that work regardless of screen size and of course sorting. 

I've designed a  good solution several times, but they also need to be a part of our design system.

You'll find some live examples (build by nvcl) on these sites, but they need refinement ;)

https://www.finansudd.dk/katalog/
https://www.dyrenesbeskyttelse.dk/adopter-et-dyr
https://www.getmore.dk/bl%C3%A6kpatroner-pris?c=305&s=3

Other and more refined examples:

https://www.asos.com/men/sale/jeans/cat/?cid=5230&ctaref=shop|jeans|mw_hp_sale
https://www.zalando.dk/herresko-sneakers/
https://www.power.dk/hvidevarer/koel-frys-og-koelefryseskabe/koelefryseskabe/pl-1215/
https://www.pricerunner.dk/cl/119/Plaeneklippere

**Comment by Bjornnyborg** [comment]
Closed, components now live at https://github.com/Novicell/novicell-components/
Repost issue on new repo, if its still a request.
