### ISSUE TITLE
Update Gulp to v4

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#249]
What does it take to update gulp to version 4?
Can we make it happen, without breaking everything?

**Comment by ankeris** [comment]
Unfortunately it breaks with the old syntax
`
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\Visual Studio Projects\novicell-frontend\node_modules\undertaker\lib\set-task.js:10:3)
. . .
`
However, it fixes some of the vulnerabilities from the older version

**Comment by Dan9boi** [comment]
closing due to #265
