### ISSUE TITLE
Sections of overlapping elements

### ISSUE THREAD

**Issue by daniel-doktor** [Novicell/novicell-frontend#258]
When I design elements that overlaps I always get the question: In what way did you think this could be made.

This is primarily a backend thing but it would be nice with some frontend examples where the backend has been in mind also. So we have this type of logic in our system.

With overlapping elements it could be 2 section overlapping – it could be a section that has a background but where the background isn't 100% in height i relations to the section, so the text overlaps the background.

Here are some examples https://web.archive.org/web/20171022094557/http://lookbook.cruxkitchen.com/
http://clorova.com/works/the-acala 
https://www.everest.agency/what-we-do 

If in doubt, don't leave it – come and ask Doktor

**Comment by Dan9boi** [comment]
So the task here is to make a "default" way of doing these overlapping sections, and do a "standard" component, that show how to do it?

**Comment by daniel-doktor** [comment]
Correctomundo!

That is my thought yes.

**Comment by Dan9boi** [comment]
@Henrikschytze 
- [ ] Make a component that can do the overlapping effect - https://ihatetomatoes.net/demos/simple-scrollmagic-tutorial/
- [ ] Make a component that can do parallax effect - http://matthew.wagerfield.com/parallax/
- [ ] Make a "Parallax page" to demo the different elements

Coordinate with the @daniel-doktor

**Comment by daniel-doktor** [comment]
How is this project coming along?

**Comment by Henrikschytze** [comment]
I'll follow up on it soon and implement parallax 👍

**Comment by Bjornnyborg** [comment]
Closed, components now live at https://github.com/Novicell/novicell-components/
Repost issue on new repo, if its still a request.
