### ISSUE TITLE
Different header styles

### ISSUE THREAD

**Issue by daniel-doktor** [Novicell/novicell-frontend#259]
Can we have som more header examples?
Left, right – navigation link, no navigation links – some without background, but where the colours in fx. logo and burger inverts (if on light background it changes to dark and vice verse).
Sticky but not horisontal, but vertical links 

http://clorova.com/works/the-acala
https://mathieulevesque.com/en
https://www.ouiwill.com/#/
https://henninglarsen.com/en

Ask Doktor if in doubt

**Comment by Bjornnyborg** [comment]
Closed, components now live at https://github.com/Novicell/novicell-components/
Repost issue on new repo, if its still a request.
