### ISSUE TITLE
Different CTA or Link styles

### ISSUE THREAD

**Issue by daniel-doktor** [Novicell/novicell-frontend#260]
Instead of just the bounding box can we try and make some different cta and link styles with some different transistions.

It could be making an overview page like this: https://tympanus.net/Development/ButtonStylesInspiration/

Here we will include the different cta and link styles.
Could be something like this: 
https://codepen.io/melnik909/pen/KGxdjY
https://codepen.io/andreasstorm/pen/oqKbLq
https://www.leeroy.ca/en
https://www.weareenvoy.com/
https://supercrowds.co/

If in doubt, ask [Doktor](https://www.novicell.dk/om-novicell/medarbejdere/daniel-doktor/)

**Comment by Bjornnyborg** [comment]
Closed, components now lives at https://github.com/Novicell/novicell-components/
