### ISSUE TITLE
Use Prettier & Beautify

### ISSUE THREAD

**Issue by heense** [Novicell/novicell-frontend#261]
Can we include Prettier and Beautify to lint our html, css and js? 

https://css-tricks.com/prettier-beautify/

https://css-tricks.com/prettier-stylelint-writing-clean-css-keeping-clean-code-two-tool-game/

**Comment by ankeris** [comment]
I have added .prettierrc file where we could add more options for code formatting on file save. However, people will have to download Prettier extension to IDE and I will write a Wiki page on how to quickly do that.

**Comment by ankeris** [comment]
There are not many options to be added now because Prettier linting is very similar to Novicell's guidelines.

**Comment by ankeris** [comment]
I have written [short tutorial on Wiki](https://github.com/Novicell/novicell-frontend/wiki/Prettier-extension-on-VSCode) on how to quickly add the extension.

**Comment by heense** [comment]
This is done
