### ISSUE TITLE
Migrate frontend guidelines to WIKI

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#264]
Go to the frontenddocs page, and migrate it to a wiki page.
The page should be using Markdown for the code examples, and should be updated from LESS to PostCSS in the docs.

https://novicell.github.io/frontenddocs/

**Comment by Henrikschytze** [comment]
Link for CSS guidelines wiki: https://github.com/Novicell/novicell-frontend/wiki/Frontend-guidelines-for-CSS

Link for HTML guidelines wiki: https://github.com/Novicell/novicell-frontend/wiki/Frontend-guidelines-for-HTML

**Comment by Dan9boi** [comment]
great work @Henrikschytze
