### ISSUE TITLE
Brand colors

### ISSUE THREAD

**Issue by magnify** [Novicell/novicell-frontend#266]
Add color presentation to the styleguide, e.g. https://www.lightningdesignsystem.com/guidelines/color or https://rizzo.lonelyplanet.com/styleguide/design-elements/colours.

**Branch:** https://issues-brand-colors-266--novicell-frontend.netlify.com/components/detail/colors.html

**To-do:**
- [x] Remove --color-blackberry
https://github.com/Novicell/novicell-frontend/blob/issues/brand-colors-%23266/patterns/design-guidelines/colors/colors.css#L16

**Comment by magnify** [comment]
[novicell-rebrand-colors-v2.0.pdf](https://github.com/Novicell/novicell-frontend/files/2629337/novicell-rebrand-colors-v2.0.pdf)

**Comment by magnify** [comment]
@Dan9boi reference for colors attached. FYI @KimDolleris.

**Comment by tbb2** [comment]
- Det  ville være smart, hvis man kunne lave et javascript, der kørte alle farvevariablerne igennem og genererede markuppen til at vise dem, så man ikke selv skulle tænke på det.

- Det ville være smart, hvis man kunne udregne rgb- og cmyk-farverne ud fra HEX-farven (med en fractal-js-function eller lignende) i stedet for at man selv skal skrive dem (i json-filen)

**Comment by KimDolleris** [comment]
Det kan man ikke helt bare sådan lige. For cmyk og rgb er 2 forskellige farverum. Det som en konvertering vil foreslå giver ikke nødvendigvis mening in real life - hvor cmyk jo hører hjemme. Så konverteringen vil sjældent være korrekt. På samme måde har pantone andre muligheder da det er forblandede farver som ikke, i trykprocessen, bliver blandet med andre farver for at give et resultat.

Det kan man også se i vores tilfælde. Men. Vi kan jo selv skrive dem i. :D

**Comment by magnify** [comment]
@tbb2 maybe we can auto generate parts of it (hex and naming) and add the rest manually (if needed). That way we avoid some duplication/replacing in css and data.

**Comment by tbb2** [comment]
@magnify I don't like the idea that we have to edit both css and data to make a color - it will fail because of both sloppyness and alzheimers

**Comment by magnify** [comment]
Ok, can we pick one place to store it: data or css? :)

What about just using css + "hardcoded" html? Is it data we want to use elsewhere?

**Comment by Dan9boi** [comment]
https://5c093227e470857ab733bf85--novicell-frontend.netlify.com/components/detail/colors.html

**Comment by magnify** [comment]
@daniel-doktor --color-blackberry should be removed?

https://github.com/Novicell/novicell-frontend/blob/issues/brand-colors-%23266/patterns/design-guidelines/colors/colors.css#L16

**Comment by daniel-doktor** [comment]
@magnify Yes sir!

**Comment by magnify** [comment]
**To-do:**
- [ ] Remove --color-blackberry
https://github.com/Novicell/novicell-frontend/blob/issues/brand-colors-%23266/patterns/design-guidelines/colors/colors.css#L16

**Comment by tbb2** [comment]
@magnify I don't think we can pick one then - the colors have to be in the css obviously, but the cmyk and pantone have to be in data
I prefer updating data to updating hardcoded HTML
I can't see that it's possible to store data in only one place... would've been really nice though
