### ISSUE TITLE
Brand typography

### ISSUE THREAD

**Issue by magnify** [Novicell/novicell-frontend#267]
Add presentation (and basic usage) of typography, e.g. https://rizzo.lonelyplanet.com/styleguide/design-elements/typography ~or https://www.lightningdesignsystem.com/guidelines/typography/~ (guidelines are being updated).

**Comment by Bjornnyborg** [comment]
Closed, this repo is not for examples, showcases or anything like that. It's only for base frontend setup. :) 
If this is still a request, you need to make it at https://github.com/Novicell/novicell-components/
