### ISSUE TITLE
Refactor existing patterns

### ISSUE THREAD

**Issue by magnify** [Novicell/novicell-frontend#269]
Some patterns needs refactoring and probably some simplifying for easier usage. E.g. https://github.com/Novicell/novicell-frontend/blob/master/patterns/01-atoms/buttons/button/button.hbs is pretty difficult to figure out at a quick glance. 

**First tasks:**
- Make a plan for refactoring existing patterns
- Find out how a new patterns is added for maintaining a healthy system

**Comment by Bjornnyborg** [comment]
Closed, components now live at https://github.com/Novicell/novicell-components/
Repost issue on new repo, if its still a request.
