### ISSUE TITLE
Don't render cookie info in _preview.hbs

### ISSUE THREAD

**Issue by magnify** [Novicell/novicell-frontend#270]
@cookie-info is rendered in _preview.hbs and loaded on all patterns. This is pretty annoying, so could we add a guide and test of the molecule instead? :)

**Comment by Dan9boi** [comment]
maybe add it to a page instead? @magnify

**Comment by magnify** [comment]
That would work too, I think the primary task at hand is to remove it from _preview.hbs. Will you assign the issue?
