### ISSUE TITLE
Support for screens on bigger resolutions

### ISSUE THREAD

**Issue by daniel-doktor** [Novicell/novicell-frontend#278]
I am looking for a setup of the grids on bigger screens.
Screen sizes like 1440px, 1600px, 1920px, 2560px.

Default screen sizes are getting larger and standard screen sizes in Denmark and the nordic countries are 1440px and 1920px http://gs.statcounter.com/screen-resolution-stats/all/denmark 

I know it is a relative thing in relations to the project – but it would be nice to make a setup – if the site is fullwidth (100% of the browsers width) that handles images, text, images with text etc.

**Comment by Dan9boi** [comment]
What should happen on the larger screensizes for images, text and so on?
What about containers? Right now i think containers have a `max-width: 1200px;`

**Comment by daniel-doktor** [comment]
What options do we have?
Can we make several versions of the grid elements?

**Comment by Dan9boi** [comment]
what do you mean by _grid elements_?
I think about the containers, should they have a new `max-width` on larger screens?
Images will be loaded in the correct way, if the containers are larger, already.
Should text's be larger on larger screens? What are the best practices?

**Comment by daniel-doktor** [comment]
With grid elements I mean the elements, objects, content – the different columns and rows with content. I am not sure what the semantics of this is with you.

They could have max-width in some cases and some cases not – that is why I think it would be nice to see some different examples.

And yes I think text should scale up proportionally.

**Comment by Dan9boi** [comment]
Max-width 2560px
Make sure to test it.
Scale font-size aswell from screensize of 1024px and up.
Make  1440px, 1600px, 1920px, 2560px media queries.

**Comment by tbb2** [comment]
We need larger screens in order to test then :-)

**Comment by Bjornnyborg** [comment]
Closed, components now live at https://github.com/Novicell/novicell-components/
Repost issue on new repo, if its still a request.
