### ISSUE TITLE
Logo download page in Fractal under "Design Guidelines" 

### ISSUE THREAD

**Issue by daniel-doktor** [Novicell/novicell-frontend#286]
Can we make a download page under "Design Guidelines" where everyone can preview and download the logos of Novicell in all its colors?

Include
RGB: png, jpg, 
[tagline-no-tagline.zip](https://github.com/Novicell/novicell-frontend/files/2844217/tagline-no-tagline.zip)
svg – red, black white
CMYK: pdf, ai – red, black white

Attached are the logo package

**Comment by Bjornnyborg** [comment]
@daniel-doktor Isnt it what this is for? :) https://www.novicell.dk/om-novicell/pressemateriale/
Also, this project is only for the base frontend setup, it doesnt contain components or examples anymore.
