### ISSUE TITLE
Sprites task Linux is returning only first file in the GLOB

### ISSUE THREAD

**Issue by shp-novicell** [Novicell/novicell-frontend#302]
Whenever I build it on Netlify (which is using Linux OS), only the first sprite is being generated. Perhaps there is shell timing problem.

**Comment by hesselberg** [comment]
https://github.com/Novicell/novicell-frontend/blob/011bca4e023008e5d20108eca514cadff19a823a/package.json#L21

Should be 

`"sprites": "cross-env-shell node config/sprites/sprite.js -i 'assets/icons/**/**/*.svg' -o $npm_package_config_DIST/icons/icons.svg"`

**Comment by Bjornnyborg** [comment]
Fixed in #305
