### ISSUE TITLE
Create component: Add class to CSS file

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#306]
Instead it would be nice, if we had the 
.component-name{
}

ready in the css file when generated (including a newline at the end of the file, to avoid angry linter)

_Originally posted by @tbb2 in https://github.com/Novicell/novicell-frontend/pull/304#issuecomment-527124916_

**Comment by Bjornnyborg** [comment]
@hesselberg also suggested to remove the default markup from the component. Maybe we should just make a div, the the class ".component-name" and render the component name as the only thing inside the div. What do you think @hesselberg and @Dan9boi ?

**Comment by hesselberg** [comment]
I think thats much better.

I've modified the script in our most recent project to do the following:

.config.json:
```{
  "title": "Organism",
  "status": "backlog",
  "context": {}
}```

.css:
```/* Insert css here */```

.hbs:
```<div></div>```

The only thing thats changing is the title in the config file to either Atom/Molecule/Organism/Page, and of course where it puts the files

**Comment by Dan9boi** [comment]
@tbb2 what do you say?

**Comment by tbb2** [comment]
What I think would be really awesome is if you can use the component name inside the files like this:

.config.json:
`
{
  "title": "my-organism-name",
  "status": "backlog",
  "context": {}
}
`
.css:
`/* Insert css here */
.my-organism-name{
}
`

.hbs:
`<div class="my-organism-name"></div>`

If not, the suggestion from @hesselberg is fine

**Comment by tbb2** [comment]
I guess I don't know how to do line-breaks inside code in this text-editor - the line-breaks should of course be as hesselberg's

**Comment by Dan9boi** [comment]
> I guess I don't know how to do line-breaks inside code in this text-editor - the line-breaks should of course be as hesselberg's

I've fixed your markdown now - just added the tripple backticks *```*.
You can see [here](https://guides.github.com/features/mastering-markdown/) how to do code with syntax highlighting and more:

**Comment by Bjornnyborg** [comment]
I reworked the generator according to your comments: https://github.com/Novicell/novicell-frontend/tree/feature/component-generator-cleaning, feedback is appreciated! :)

**Comment by Bjornnyborg** [comment]
`createComponent -t a -n "My Component"` generates:

```json
{
  "title": "My Component",
  "status": "prototype",
  "context": {
  }
}
```
.css:
```css
.my-component {
}
```

.hbs:
```handlebars
<div class="my-component"></div>
```

**Comment by tbb2** [comment]
It's nice! I think it would be nicer though, if you write the class name when you create the component
´´´createComponent -t a -n "my-component"´´´
since that is the most important name for the developer - actually you only see the title from the json file if you're working in fractal.

Whether you want to leave the dashes in the title in the json file or replace them with spaces and capitalize first letter in each word - I don't have an opinion on that...

**Comment by hesselberg** [comment]
The title in the JSON file is just as important, as it generates the title in Fractal. Loving everything else!

**Comment by tbb2** [comment]
The title in the JSON file only generates the title that is shown above the preview iframe in fractal. The title in the navigation in fractal is generated from the folder name instead

**Comment by Bjornnyborg** [comment]
I updated the generator, now the name argument is used directly as file/folder name, and a capitalized version with spaces instead of dashes, is used as the title. :)

**Comment by tbb2** [comment]
@Bjornnyborg I think that's splendid

**Comment by Dan9boi** [comment]
i guess this can be closed due to @Bjornnyborg 's commit?
