### ISSUE TITLE
Use production Vue

### ISSUE THREAD

**Issue by sebimoe** [Novicell/novicell-frontend#317]
When building for production (`build:prod`) development distribution of Vue is included. (Verifiable by console warning if you install vue and import it in the project)

I submit a pull request to include .min.js distribution (production mode build) in production environment, but I am not sure why Vue needs to be explicitly aliased there rather than imported.

**Comment by Dan9boi** [comment]
@ankeris do you have any comments to this?
Maybe some insights?
