### ISSUE TITLE
Replace uglify with terser

### ISSUE THREAD

**Issue by soreng** [Novicell/novicell-frontend#328]
npm install terser-webpack-plugin --save-dev
npm uninstall uglifyjs-webpack-plugin 
npm uninstall uglify-js

in webpack.config.js we replaced the uglify plugin, but retained the same options:

```
            new TerserPlugin({
                sourceMap: true,
                terserOptions: {
                    ecma: 8,
                    mangle: false,
                    keep_classnames: true,
                    keep_fnames: true
                }
            })

```

**Comment by Dan9boi** [comment]
good job @soreng 💯

**Comment by hesselberg** [comment]
@soreng how come we're doing this?

**Comment by Dan9boi** [comment]
@hesselberg actually what they say on github:
>**Why choose terser?**
>uglify-es is no longer maintained and uglify-js does not support ES6+.
>
>terser is a fork of uglify-es that mostly retains API and CLI compatibility with uglify-es and uglify-js@3.
@soreng

**Comment by hesselberg** [comment]
@Dan9boi all good, just think its important we document/explain why we are doing things :-)
