### ISSUE TITLE
Flexbox grid

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#40]
Look into flexboxgrid.com and make new cool grid using flexbox and all it's goodness :muscle:

**Comment by hesselberg** [comment]
@Dan9boi are we comfortable with the support on flexbox? While we have more or less dropped all support for IE9 and below, flexbox isn't failfree in IE11.

http://caniuse.com/#feat=flexbox

Check the known issues tab at the bottom

**Comment by Dan9boi** [comment]
This issue is put on hold due to lacking support of flexbox in IE11. Right now statistics say IE11 has about 8% (8% Denmark and 4% globally) of the users, which is too many users having issues with this new feature. We will have a look at this at again in a near future, when IE11 drop below 5%.

**Comment by hesselberg** [comment]
Reopening this issue - this is something we would like to revisit each month, and discuss if we are ready for it.

**Comment by Dan9boi** [comment]
@Nesuarg can i get a status of the testing?

**Comment by hesselberg** [comment]
Don't forget documentation

**Comment by shp-novicell** [comment]
Also revisit breakpoints (#128)

**Comment by Dan9boi** [comment]
1 year, happy birthday! 🎂

**Comment by Dan9boi** [comment]
i've added this as a dependency
