### ISSUE TITLE
Split JS plugins into separate repos

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#41]
Split all js plugins into separate repos to make easier maintenance and separation of concerns. This is also for not bloating this repository with files not necessarily being used on all projects.

We can then load the the scripts through NPM and extend them via the new syntax mentioned #111.
**Make sure the change the scripts to the new syntax, when moving into seperate repos.**

**Comment by hesselberg** [comment]
Pushed to next milestone, as we aren't sure of the impact of this. We still want to do it, but, it will have major impact when we start new projects.

**Comment by Dan9boi** [comment]
Would it make sense to load each plugin through bower?
What is the pros / cons?
@hesselberg @jhavmoeller

**Comment by hesselberg** [comment]
Where did we end up regarding this? Perhaps it should be a topic for the next frontend meeting? @Dan9boi

**Comment by Dan9boi** [comment]
Yes that sounds like a good idea @hesselberg

**Comment by Dan9boi** [comment]
**Cookie info:** https://github.com/Novicell/novicell-cookie-info
Codereview: @Havmoeller @jhavmoeller please 🙏

**Comment by shp-novicell** [comment]
Closed due to new seperate issues.
