### ISSUE TITLE
SVG bundles

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#49]
Make it possible to make multiple SVG sprites, as bundles, eg. for use in CMS backends.
I guess all that needs to be done, is renaming the sprite outputname to the name of the bundle. Find a renaming module and do something like:

``` javascript
.pipe(...)
.pipe(rename(b.name + '.svg'))
.pipe(gulp.dest(config.iconsDist));
```

**Comment by Dan9boi** [comment]
@marklonquist can you do a codereview and merge this?

**Comment by hesselberg** [comment]
Awesome!
