### ISSUE TITLE
Look at srcset

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#58]
Look at srcset, and figure out if it could replace the focalpoint image, and make a remarkable simpler js method to lazyload images.
At the time of writing this, IE11 is the only broser which is not supporting the srcset, but maybe this could be fixed with a polyfill. IE11 is at 9.4% market share in Denmark.

http://caniuse.com/#search=srcset

**Comment by hesselberg** [comment]
Regarding IE11, it really doesn't matter as the default should just be whatever is the desktop size, and, IE11 can only run on desktop.

We're testing srcsets out right now on KILROY -- it's working well so far, but haven't gotten the customer input yet.

**Comment by Dan9boi** [comment]
I think we can just start using it today, if we combine it with this polyfill.io _polyfill as a service_ https://polyfill.io/v2/docs/

@hesselberg can you bring some insights from the KILROY project? How are you getting the different image sizes, from the CMS? Are you using imageprocessor or something else? What about art direction in the sizes?

**Comment by Dan9boi** [comment]
@shp-novicell will test this out on her next project.

**Comment by Dan9boi** [comment]
I'm closing this issue as we have tested srcset on multiple projects counting Kilroy, COOP and DEIF. All of these have been great experiences. Go to @shp-novicell @emilankersen or me, to get more information.
