### ISSUE TITLE
Split framework from build setup

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#59]
Divide the frontend framework (scripts and less) from the gulp build setup.
These two things does not directly depend on each other, and should be in separate repos, for easier maintenance.
If we do this, it could be possible to update the gulp build setup separately from the project files like, less components and so on.

**Comment by Dan9boi** [comment]
Does anyone have an opinion about this?

**Comment by hesselberg** [comment]
Hmm, we already talked about splitting each component in its own repo -- wouldn't this then be obsolete? I'm guessing we should keep the `base`, `mixins` and `settings` folders?

**Comment by Dan9boi** [comment]
But as we do it now, we ship with the less "framework" but this is also made for cusomization. This makes it difficult to update the build tool without "updating" the customized framework aswell... That's why i think it would make sense to seperate the js/less from the build tool itself.

Then we would have the ability to update the build tool without touching the framework/source files of the project.

It will make it a bit more complex, when you use both the build tool and the framework manually, but for most projects, this would be handled by the installer. But in the end, it is just 2 repos that need cloning.
@Novicell/core

**Comment by Dan9boi** [comment]
doesn't seem like a good idea...
