### ISSUE TITLE
Merge the javasscript lazyload files

### ISSUE THREAD

**Issue by hesselberg** [Novicell/novicell-frontend#6]
Looking at https://github.com/Novicell/novicell-frontend/blob/master/scripts/components/novicell.lazyload.js and https://github.com/Novicell/novicell-frontend/blob/master/scripts/components/novicell.lazyloadResponsive.js, there are some similarities. 

Perhaps we should look into merging them, and maybe remove the lazyload image function, that doesn't take responsiveness into account?

**Comment by Dan9boi** [comment]
Please fix :+1: @hesselberg

**Comment by Dan9boi** [comment]
Is anyone using the "lazyload.content"? Should we keep it?

**Comment by marklonquist** [comment]
I've only ever used the lazyloadresponsive.js lib

**Comment by hesselberg** [comment]
We've decided to remove the old lazyload script (novicell.lazyload.js), and only continue with the new responsive one.
