### ISSUE TITLE
only process changed files

### ISSUE THREAD

**Issue by soreng** [Novicell/novicell-frontend#61]
http://gulpjs.org/recipes/only-pass-through-changed-files.html

to help speedup gulp'ing, we could ignore the files that haven't been changed.

**Comment by hesselberg** [comment]
+1

**Comment by Dan9boi** [comment]
I remember that we had this running at some point. As i recall it took just as long time for `gulp-changed` to see if things have changed, as it took to just make new files.

@marklonquist make sure to test timing with / without the `gulp-changed` package...

**Comment by hesselberg** [comment]
Moved assignee to @Dan9boi, as @marklonquist seems to be occupied with other tasks

**Comment by Dan9boi** [comment]
I don't think this would work as the example code in the link only handles the changed files. This will (if i get this right) that we are going to make a new bundle file, with only the files changed, and not all the files in the bundle :(

**Comment by Dan9boi** [comment]
As we are working on a new build system without gulp, i will consider this, when we build our new build tool, and close this issue.
