### ISSUE TITLE
Move dummy/test files to examples/test folder

### ISSUE THREAD

**Issue by hesselberg** [Novicell/novicell-frontend#7]
Hola,

We can add a `.npmignore` file to the repo that makes sure we don't add example files such as https://github.com/Novicell/novicell-frontend/blob/master/images/map-pin.png.

So, when you are working on the package, you can get the files, but when someone uses the package for a new project, they won't get them.

Makes sense? We can discuss it further in person.

**Comment by Dan9boi** [comment]
Please do it.

**Comment by hesselberg** [comment]
Okay so, I moved all the development files of the package to a subfolder called examples. I've also updated the package.json, to be more descriptive.

Originally we wanted to exclude development files when cloning the project, but alas, it doesn't seem to be possible. Using a `.npmignore` will just overwrite the `.gitignore`. Therefore, lets stick to the `.gitignore`.
