### ISSUE TITLE
Add a way to force height to the image in lazy load responsive

### ISSUE THREAD

**Issue by SergiSMJ** [Novicell/novicell-frontend#74]
I don't know if I miss something but sometimes I have problems with the height on the images with this plugin, the problem was that there is not a way to force the height of the image and crop it. To solve this I modified the plugin to be able to do this, If you interested in this change I can do a pull request.

**Comment by Dan9boi** [comment]
hi, @SergiSMJ 
Can you use the height-ratio for changing the ratio of the image?
Or are you looking for a way to force a specific height?

**Comment by SergiSMJ** [comment]
Hi @Dan9boi 
Yes this change is to be able to force a specific height :)

**Comment by Dan9boi** [comment]
@Havmoeller can you have a look at this?

**Comment by hesselberg** [comment]
@jhavmoeller ping

**Comment by SergiSMJ** [comment]
The PR is merged, I close this!
