### ISSUE TITLE
Rebuild node-sass

### ISSUE THREAD

**Issue by MKAndersen** [Novicell/novicell-frontend#76]
Every time npm is installed through visual studio , when we run gulp through git bash afterwards it requires to rebuild node-sass

**Comment by Dan9boi** [comment]
I think @marklonquist has a solution for this issue.

**Comment by marklonquist** [comment]
Tools > Options > Projects and Solutions > External Web Tools > Move $(PATH) up so it's the 2nd value.

![2016-10-28 12_17_12-start page - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/1456819/19803351/7d33f292-9d08-11e6-989a-1d4476999149.png)

**Comment by hesselberg** [comment]
Awesome! Perhaps we should create a FAQ, or a common issues list, in the Wiki? This could be a good start for it

**Comment by Dan9boi** [comment]
@MKAndersen does this help you?

**Comment by Dan9boi** [comment]
Added to the WIKI FAQ: https://github.com/Novicell/novicell-frontend/wiki/Frequently-asked-questions
