### ISSUE TITLE
Specific gutters on different breakpoints

### ISSUE THREAD

**Issue by hesselberg** [Novicell/novicell-frontend#8]
Had a chat with @KimDolleris about adding specific gutters on different breakpoints. Say on a tablet we want a gutter on 30px, but on desktop we want it to be 40px.

mixins.grid.less:22
```
// Generate the extra small columns
.make-xs--column(@columns) {
    position: relative;
    float: left;
    width: percentage((@columns / @grid-columns));
    min-height: 1px;
    padding-left:  (@gutter / 2);
    padding-right: (@gutter / 2);
}
```

Looking at the above code, I guess we could add various variables for the gutter, so, maybe something like `@xs-gutter`, and so on for each breakpoint. By default they should all reference the main `@gutter`, but this does give each project the possibility of adding different gutters.

Thoughts? Let's discuss!

**Comment by KimDolleris** [comment]
Great idea

**Comment by Dan9boi** [comment]
I think it's a great idea, though we don't use it a lot right now. If we just set it as default, then it's possible to change it as per breakpoint, on all new projects, I think it will be fine...
I have no "cons" for the suggestion :)

**Comment by hesselberg** [comment]
Cool, I'll try and implement it this weekend 👍

**Comment by hesselberg** [comment]
Some thoughts so far; 

The way we currently output the grid and the columns is based on a looping mixin. In a nutshell this means that to change the padding based on the media query, it will have to affect all of the columns. This means the compiled stylesheet will grow with about 3kb (minified). Is this acceptable?

Also, we haven't discussed what happens with the container and the rows. Should they keep their original 15px gutter, or will they also adapt to the custom gutter, depending on media queries?

@Dan9boi @KimDolleris

**Comment by Dan9boi** [comment]
#9
