### ISSUE TITLE
Consider moving focalpoint from the Novicell frontend to the Novicell Umbraco

### ISSUE THREAD

**Issue by hesselberg** [Novicell/novicell-frontend#82]
Currently the focalpoint is just an option for Umbraco. Because of this, I don't think it should be a part of the Novicell frontend, as it isn't cross platform friendly.

Discuss!

**Comment by Dan9boi** [comment]
@marklonquist @msoelvsteen

**Comment by Dan9boi** [comment]
Great idea, i'll take this one.

**Comment by Dan9boi** [comment]
fixed here: https://github.com/Novicell/novicell-frontend/commit/36b97b9835471efe1c5e8d15cdcc9e3960c2f960
