### ISSUE TITLE
Use Webpack

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#83]
Consider switching build setup from Gulp to Webpack (4).
Does anyone have experience with Webpack?

https://blog.madewithenvy.com/getting-started-with-webpack-2-ed2b86c68783#.qkfrveivf

**Comment by hesselberg** [comment]
@marklonquist !

**Comment by shp-novicell** [comment]
Closed due to #120

**Comment by tbb2** [comment]
closed due to #265
