### ISSUE TITLE
When (npm) installing the packages under node v7.1.0 warnings are given

### ISSUE THREAD

**Issue by soreng** [Novicell/novicell-frontend#84]
the following warnings are issued when executing npm install on a "blank" machine:

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global mimer@0.2.1 should be installed with -g
npm WARN prefer global jsonlint@1.6.2 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

The dependency-tree for graceful-fs is:

+-- gulp@3.9.1
| -- vinyl-fs@0.3.14
|   +-- glob-watcher@0.0.6
|   | -- gaze@0.5.2
|   |   -- globule@0.1.0
|   |     -- glob@3.1.21
|   |       -- graceful-fs@1.2.3
|   -- graceful-fs@3.0.11
+-- gulp-sourcemaps@1.9.0
| -- graceful-fs@4.1.10
-- remove-svg-properties@0.3.3
  -- graceful-fs@3.0.11

**Comment by hesselberg** [comment]
@soreng ... and this issue is about what sorry? :-) graceful-fs is a dependency on some of the other packages that we've included in the package. I guess some of the packages depends on a specific version.

**Comment by soreng** [comment]
@hesselberg I know

I was triggered by the message:
> will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible.

Shouldn't we upgrade the packages using the old version?

**Comment by hesselberg** [comment]
I think thats a great idea if it solves the problem :-) Make a PR and I'll merge it in

**Comment by Dan9boi** [comment]
I just updated our own dependencies, can you try to see if this gives any different result? @soreng

**Comment by Dan9boi** [comment]
@soreng can you look at this before the end of the milestone?

**Comment by soreng** [comment]
Hi, Yes I will have a look at it within the next week or so :-)

**Comment by Dan9boi** [comment]
@soreng  ...?

**Comment by Dan9boi** [comment]
I will take this issue, and update all our own dependencies @soreng
