### ISSUE TITLE
Remove gulp-sass

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#86]
This package is the default foundation for Novicell Projects.
In Novicell we always use LESScss, and I see no reason why this package should support SASS / SCSS when we do not use it.

**Comment by hesselberg** [comment]
Can we dig out why we addede SASS support? I know it wasn't a part of the original scope, but it was added later on.

**Comment by Dan9boi** [comment]
I guess it was for a project that should use Foundation, and I wanted us to be able to continue using Bootstrap with version 4 where they switched to SASS instead of LESS...

Seems like we are not going to need it for either of those frameworks anyway...

**Comment by Dan9boi** [comment]
cloed due to Remove gulp-sass #87
