### ISSUE TITLE
50% of the source code for the grid isn't used?

### ISSUE THREAD

**Issue by hesselberg** [Novicell/novicell-frontend#91]
While creating a grid based off on the grid in novicell-frontend, I found out that about 50% of the source code isn't even used.

Perhaps we should look into cleaning it, while we're also looking at using the flexbox grid in #40 ?

**Comment by Dan9boi** [comment]
Lars will copy his findings before january.

**Comment by Dan9boi** [comment]
This will be obsolete as of making the new flexbox grid in isuue #40
