### ISSUE TITLE
Add FTP deploy task

### ISSUE THREAD

**Issue by Dan9boi** [Novicell/novicell-frontend#98]
For use for HTML task.
We can use the node module `gulp-ftp`
https://www.npmjs.com/package/gulp-ftp

**Comment by emilras** [comment]
Fascinating that ftp is still used nowadays. Just to satisfy my curiosity, what are the scenarios this is need in?

Ftp is not really secure, is it possible to use sftp?

**Comment by Dan9boi** [comment]
@emilras it's only for deploying prototypes for the beneath website.

**Comment by emilras** [comment]
@Dan9boi Ok, makes sense. Ftp without the s activates the paranoid centers in my brain :)

**Comment by Dan9boi** [comment]
@shp-novicell see if you can force/default to **S**FTP 🥇
